@startuml DomainModel
package JobOpeningAgg {

    class JobOpening {
        +id: JobReference
        +title: JobOpeningTitle
        +requirements: RequirementsSpecification
    }

    class Phase {
        +id: PhaseName
    }

    enum PhaseName {
        SCREENING
    }

    JobOpening --> RecruitmentProcess
    RecruitmentProcess --> Phase
    Phase --> PhaseName: "Is in phase"
}

package ApplicationAgg {
    class Application {
        +id: ApplicationID
        +interview: Interview
        +status: ApplicationStatus
    }


    enum ApplicationStateName {
        Pending
        Accepted
        Rejected
    }


    Application --> JobOpening : Refers to

    Application --> ApplicationStateName
}

package RequirementsSpecificationAgg {

    class RequirementsSpecification {
        +id: RequirementsSpecificationID
        +skills: List<Skill>
        +experience: Experience
    }

    class Description {
        +name: String
    }

    class JarFile {
        +years: Int
    }
    class SpecName {
        +name: String
    }

    JobOpening --> RequirementsSpecification : Has
    RequirementsSpecification --> Description
    RequirementsSpecification --> JarFile
    RequirementsSpecification --> SpecName

}

package CandidateAgg {
    class Candidate {
        +email: CandidateEmail
        +name: CandidateName
    }

    class CandidateEmail {
        +email: String
    }

    class CandidateName {
        +firstName: String
        +lastName: String
    }

    Application --> Candidate : Is submitted by
    Candidate --> CandidateEmail
    Candidate --> CandidateName

}




@enduml
