@startuml

title SD - Add User

actor Administrator
participant "UI : AddUserUI" as UI
participant "Controller : AddUserController" as controller
participant "Service : UserManagementService" as userService

Administrator -> UI : initiateAddUser()
activate UI

UI -> UI : getUserInput()
UI -> controller : addUser(username, password, firstName, lastName, email, roles)
activate controller

controller -> userService : registerNewUser(username, password, firstName, lastName, email, roles)
activate userService
userService --> controller : SystemUser
deactivate userService

controller --> UI : displaySuccess()
deactivate controller

UI --> Administrator : showResult()

deactivate UI

@enduml
