@startuml SystemSequenceDiagram

title US1016 - Notify Candidates by Email

actor CustomerManager
participant ":System" as S

CustomerManager -> S: Notify Candidates
S --> CustomerManager: Confirm sent notifications
@enduml
