@startuml
actor CustomerManager as CM
participant System

CM -> System : Requests to rank the candidates for a job opening
System --> CM : Returns the list of job openings and asks to select one
CM -> System : Selects a job opening

alt in Analysis
    System --> CM : Returns the options candidates ranked\nand candidates not ranked
    CM -> System : Selects one of the options
    loop for each candidate
        System --> CM : Returns candidate
        CM -> System : Ranks the candidate
    end
else not in Analysis
    System --> CM : Returns the message "The job opening is not in the Analysis phase"
end
@enduml