@startuml
actor CustomerManager
boundary ListOrderedApplicationsUI
control ListOrderedApplicationsController
control OrderApplicationsService
entity JobOpeningRepository
entity ApplicationRepository
entity RecruitmentProcess
entity jobApplication

CustomerManager -> ListOrderedApplicationsUI: doShow()
activate ListOrderedApplicationsUI

ListOrderedApplicationsUI -> CustomerManager: askForJobReference()
CustomerManager -> ListOrderedApplicationsUI: Input job reference

ListOrderedApplicationsUI -> ListOrderedApplicationsController: validateJobReference(jobReference)
activate ListOrderedApplicationsController

ListOrderedApplicationsController -> JobOpeningRepository: findByJobReference(jobReference)
activate JobOpeningRepository
JobOpeningRepository --> ListOrderedApplicationsController: JobOpening
deactivate JobOpeningRepository


ListOrderedApplicationsController -> OrderApplicationsService: create(recruitmentProcess : RecruitmentProcess)
activate OrderApplicationsService
OrderApplicationsService --> ListOrderedApplicationsController: orderApplicationsService
deactivate OrderApplicationsService

ListOrderedApplicationsController -> ApplicationRepository: findByJobReference(jobReference)
activate ApplicationRepository
ApplicationRepository --> ListOrderedApplicationsController: List<jobApplication>
deactivate ApplicationRepository

ListOrderedApplicationsController -> OrderApplicationsService: orderedListOfApplications(applications)
activate OrderApplicationsService


OrderApplicationsService -> OrderApplicationsService: validateCurrentPhase()
activate OrderApplicationsService
deactivate OrderApplicationsService
OrderApplicationsService -> OrderApplicationsService: sort(applications)
activate OrderApplicationsService
deactivate OrderApplicationsService
OrderApplicationsService --> ListOrderedApplicationsController: List<jobApplication>
deactivate OrderApplicationsService

ListOrderedApplicationsController --> ListOrderedApplicationsUI: List<jobApplication>
deactivate ListOrderedApplicationsController


ListOrderedApplicationsUI -> CustomerManager: Display ordered applications
deactivate ListOrderedApplicationsUI
@enduml
