@startuml

title SD - List Job Openings

actor User
participant "UI : ListJobOpeningsUI" as UI
participant "Controller : ListJobOpeningsController" as controller
participant "Repository : JobOpeningRepository" as repository

User -> UI : show()
activate UI

UI -> controller : allJobOpenings()
activate controller

controller -> repository : findAll()
activate repository
repository --> controller : List<JobOpening>
deactivate repository

controller --> UI : List<JobOpening>
deactivate controller

UI -> UI : displayJobOpenings(List<JobOpening>)

UI --> User : renderJobOpenings()
deactivate UI

@enduml
