@startuml DomainModel
package JobOpeningAgg {

    class JobOpening {
        +id: JobReference
        +title: JobOpeningTitle
    }

    class Phase {
        +id: PhaseName
    }

    enum PhaseName {
        ANALYSIS
    }

    JobOpening --> Phase : "Is in phase"
    Phase --> PhaseName
}

package ApplicationAgg {
    class Application {
        +id: ApplicationID
        +interview: Interview
    }

    class Interview {
        +grade: InterviewGrade
        +justification: String
    }


    class InterviewGrade {
        +grade: int
    }

    Application --> Interview
    Application --> JobOpening : Refers to
    Interview --> InterviewGrade
}

package CandidateAgg {
    class Candidate {
        +email: CandidateEmail
        +name: CandidateName
    }

    class CandidateEmail {
        +email: String
    }

    class CandidateName {
        +firstName: String
        +lastName: String
    }

    Application --> Candidate : Is submitted by
    Candidate --> CandidateEmail
    Candidate --> CandidateName
}


@enduml
