@startuml DomainModel
package JobOpeningAgg {

    class JobOpening {
        +id: JobReference
        +title: JobOpeningTitle
    }

    class Phase {
        +id: PhaseName
    }

    enum PhaseName {
        ANALYSIS
    }

    JobOpening --> RecruitmentProcess
    RecruitmentProcess --> Phase
    Phase --> PhaseName: "Is in phase"

    JobOpening --> RequirementsSpecification
}

package ApplicationAgg {
    class Application {
        +id: ApplicationID
        +interview: Interview
    }

    class Interview {
        +grade: InterviewGrade
        +justification: String
    }


    class InterviewGrade {
        +grade: int
    }

    Application --> Interview
    Application --> JobOpening : Refers to
    Interview --> InterviewGrade

    class RequirementsEvaluation<<Enum>>

    Application "1" --> "1" RequirementsEvaluation
}


package RequirementsSpecificationAgg {
    class RequirementsSpecification<<Root>><<Entity>>
    class JarFile<<Value Object>>
    class SpecName<<Value Object>><<Id>>
    class Description<<Value Object>>

    RequirementsSpecification "1" --> "1" JarFile
    RequirementsSpecification "1" --> "1" SpecName
    RequirementsSpecification "1" --> "1" Description

    JobOpening --> RequirementsSpecification
}



package CandidateAgg {
    class Candidate {
        +email: CandidateEmail
        +name: CandidateName
    }

    class CandidateEmail {
        +email: String
    }

    class CandidateName {
        +firstName: String
        +lastName: String
    }

    Application --> Candidate : Is submitted by
    Candidate --> CandidateEmail
    Candidate --> CandidateName
}


@enduml
