@startuml


title Register Customer User - US1001

actor CustomManager as "CustomManager"


CustomManager -> System: 1. Requests to create a new customer user
System --> CustomManager: 1.1 Displays form for customer user details


CustomManager -> System: 2. Enters customer's name and email
System --> CustomManager: 2.1 Asks for confirmation of details


CustomManager -> System: 3. Confirms details
System --> CustomManager: 3.2 Customer user created successfully

@enduml
