@startuml
'https://plantuml.com/class-diagram

hide field
hide methods

title Domain Driven Design
skinparam linetype ortho

package InterviewAgg #A9A9A9 {

    class Interview<<Root>><<Entity>>
    class InterviewID<<Value Object>><<Id>>
    class InterviewQuestions<<Value Object>>
    class InterviewAnswers<<Value Object>>

    Interview "1" --> "1" InterviewID
    Interview-->"1"InterviewQuestions
    Interview-->"1"InterviewAnswers

}

package InterviewModelAgg #808080 {

    class InterviewModel<<Root>><<Entity>>

    class JarFile<<Value Object>>
    class SpecName<<Value Object>><<Id>>
    class Description<<Value Object>>


    InterviewModel-->"1"JarFile
    InterviewModel-->"1"SpecName
    InterviewModel-->"1"Description


    Interview --> InterviewModel : Makes


}

package ClientAgg #696969 {

    class Client<<Entity>><<Root>>
    class ClientID<<Value Object>><<Id>>
    class Name<<Value Object>>
    class Address<<Value Object>>
    class ClientRepresentative<<Entity>>

    class Email<<Value Object>><<Id>>
    class PhoneNumber<<Value Object>>
    class FullName<<Value Object>>

    class Password<<Value Object>>

    Client "1" --> "1" ClientID
    Client "1" --> "1" Name
    Client "1" --> "1" Address
    Client "1" --> "1" ClientRepresentative

    ClientRepresentative "1" --> "1" Email
    ClientRepresentative "1" --> "1" PhoneNumber
    ClientRepresentative "1" --> "1" FullName
    ClientRepresentative "1" --> "1" Password



}

package JobOpeningAgg #778899 {

    class JobOpening<<Root>><<Entity>>
    class JobReference<<Value Object>><<Id>>
    class Phase<<Value Object>>
    class Duration<<Value Object>>
    class NrVacancies<<Value Object>>
    class Title<<Value Object>>
    class ContractType<<Value Object>>
    class Description<<Value Object>>
    class Address<<Value Object>>
    class Mode<<Value Object>>
    class Requirements<<Value Object>>

    JobOpening "1" --> "1" JobReference
    JobOpening "1" --> "1" Phase
    JobOpening "1" --> "1" Duration
    JobOpening "1" --> "1" NrVacancies
    JobOpening "1" --> "1" Title
    JobOpening "1" --> "1" ContractType
    JobOpening "1" --> "1" Description
    JobOpening "1" --> "1" Address
    JobOpening "1" --> "1" Mode
    JobOpening "1" --> "1" Requirements

    Client --> JobOpening : Creates


}

package RequirementsSpecificationAgg #708090 {

    class RequirementsSpecification<<Root>><<Service>>
    class JarFile<<Value Object>>
    class SpecName<<Value Object>><<Id>>
    class Description<<Value Object>>

    RequirementsSpecification "1" --> "1" JarFile
    RequirementsSpecification "1" --> "1" SpecName
    RequirementsSpecification "1" --> "1" Description

    JobOpening --> RequirementsSpecification : Has
}

package CandidateAgg #778899 {

    class Candidate<<Root>><<Entity>>
    class Email<<Value Object>><<Id>>
    class Name<<Value Object>>
    class PhoneNumber<<Value Object>>
    class Password<<Value Object>>

    Candidate "1" --> "1" Email
    Candidate "1" --> "1" Name
    Candidate "1" --> "1" PhoneNumber
    Candidate "1" --> "1" Password

}

package ApplicationAgg #696969 {

    class Application<<Root>><<Entity>>
    class ApplicationID<<Value Object>>
    class ApplicationData<<Value Object>>
    class ApplicationEmailContent<<Value Object>>
    class ApplicationState<<Entity>>
    class ApplicationStateID <<Value Object>>
    class ApplicationRanking<<Entity>>
    class RequirementsResult<<Value Object>>
    class InterviewResults<<Value Object>>
    class ApplicationStateDate<<Value Object>>

    Application "1" --> "1" ApplicationID
    Application "1" --> "1" ApplicationState
    Application "1" --> "1" ApplicationData
    Application "1" --> "1" ApplicationEmailContent
    Application "1" --> "1" ApplicationRanking
    ApplicationState "1" --> "1" ApplicationStateDate
    ApplicationState "1" --> "1" ApplicationStateID

    Candidate --> Application : Makes
    Application --> JobOpening : Refers

    Application --> RequirementsSpecification : is evaluated by
    Interview-->Application : Refers
    ApplicationRanking --> InterviewResults : Has
    ApplicationRanking --> RequirementsResult : Has

    InterviewModel --> InterviewResults : Refers
    RequirementsSpecification --> RequirementsResult : Refers



}




@enduml