@startuml

skinparam package {
  BackgroundColor<<root>> LightGreen
  BackgroundColor<<value object>> LightBlue
  BackgroundColor<<entity>> LightYellow
}

package "ClientAgg" {
  class Client <<root>> {
  }
  class ClientID <<value object>> {}
  Client "1" -- "1" ClientID

  class Name <<value object>> {}
  class Address <<value object>> {}
  Client "1" -- "1" Name
  Client "1" -- "1" Address

  class ClientRepresentative <<entity>> {
  }
  class RepresentativeID <<value object>> {}
  class Email <<value object>> {}
  class PhoneNumber <<value object>> {}
  class FullName <<value object>> {}
  class ShortName <<value object>> {}
  class Password <<value object>> {}
  ClientRepresentative "1" -- "1" RepresentativeID
  ClientRepresentative "1" -- "1" Email
  ClientRepresentative "1" -- "1" PhoneNumber
  ClientRepresentative "1" -- "1" FullName
  ClientRepresentative "1" -- "1" ShortName
  ClientRepresentative "1" -- "1" Password

  Client "1" -- "1" ClientRepresentative
}

package "JobOpeningAgg" {
  class JobOpening <<root>> {
  }


  class JobReference <<value object>> {}
  class Phase <<value object>> {}
  class Duration <<value object>> {}
  class NrVacancies <<value object>> {}
  class Title <<value object>> {}
  class ContractType <<value object>> {}
  class Description <<value object>> {}
  class Address <<value object>> {}
  class Mode <<value object>> {}
  JobOpening "1" -- "1" JobReference
  JobOpening "1" -- "1" Phase
  JobOpening "1" -- "1" Duration
  JobOpening "1" -- "1" NrVacancies
  JobOpening "1" -- "1" Title
  JobOpening "1" -- "1" ContractType
  JobOpening "1" -- "1" Description
  JobOpening "1" -- "1" Address
  JobOpening "1" -- "1" Mode

  ClientID --> JobOpening : Creates
}

package "RequirementsSpecificationAgg" {
  class RequirementsSpecification <<root>> {
  }

  class JarFile <<value object>> {}
  class SpecName <<value object>> {}
  RequirementsSpecification "1" -- "1" JarFile
  RequirementsSpecification "1" -- "1" SpecName

  JobReference --> RequirementsSpecification : Has
}
package "CandidateAgg" {
  class Candidate <<root>> {
  }
  class CandidateID <<value object>> {}
  class CandidateEmail <<value object>> {}
  class CandidateName <<value object>> {}
  class CandidatePhoneNumber <<value object>> {}
  Candidate "1" -- "1" CandidateID
  Candidate "1" -- "1" CandidateEmail
  Candidate "1" -- "1" CandidateName
  Candidate "1" -- "1" CandidatePhoneNumber
}

package "ApplicationAgg" {
  class Application <<root>> {
  }
  class ApplicationID <<value object>> {}
  class ApplicationState <<value object>> {}
  Application "1" -- "1" ApplicationID
  Application "1" -- "1" ApplicationState

  CandidateID --> Application : Makes
  ApplicationID --> JobReference : Refers
}

package "RequirementsEvaluationAgg" {
  class RequirementsEvaluation <<root>> {
  }
  class RequirementsResults <<value object>> {}
  RequirementsEvaluation "1" -- "1" RequirementsResults

  ApplicationID --> RequirementsEvaluation : Evaluates
  RequirementsSpecification --> RequirementsEvaluation : Evaluates
}

@enduml         