@startuml


    class UploadRequirementsController {
        + getApplications(): Iterable<jobApplication>
        + uploadTextFile(application: jobApplication, path: String)
        - extractAfterSecondColon(line: String): String
        - readFileLines(filePath: String): List<String>
    }



    class UploadRequirementsUI {
        - controller: UploadRequirementsController
        + doShow(): boolean
        + headline(): String
        - listHeader(): String
    }



    class ApplicationService {
        + findAll(): Iterable
        + uploadRequirementsResponses(application: jobApplication, responses: String)
    }



    class jobApplication


UploadRequirementsUI --> UploadRequirementsController
UploadRequirementsController --> ApplicationService
UploadRequirementsController --> jobApplication


@enduml
