@startuml
hide field
hide methods

title Domain Driven Design
skinparam linetype wavy

package ApplicationAgg #aaaabb {
    class Application<<Root>><<Entity>>
    class ApplicationID<<Value Object>><<Id>>

    class FilePath<<Value Object>>
    class File<<Value Object>>
    class FileType<<Enum>>

    class RejectionJustification<<Value Object>>
    class InterviewDateTime<<Value Object>>

    class ApplicationState<<Entity>>
    class ApplicationStateName<<Enum>><<ID>>

    class RequirementsEvaluation<<Enum>>

    class Interview<<Value Object>>
    class InterviewGrade<<Value Object>>

    Application "1" --> "1" ApplicationID
    Application "1" --> "1" ApplicationState
    ApplicationState "1" --> "1" ApplicationStateName
    ApplicationState "1" --> "0..1" RejectionJustification
    Application "1" --> "0..1" Interview
    Application "1" --> "*" File

    Application "1" --> "1" RequirementsEvaluation

    File "1" --> "1" FilePath
    File "1" --> "1" FileType

    Interview "1" --> "0..1" InterviewGrade
    Interview "1" --> "1" InterviewDateTime

    Application "0..*" --> "1" JobOpening : Refers to
    Application "1..*" --> "1" Candidate : Is submitted by
}

ApplicationAgg ..> CandidateAgg : Is submitted by
ApplicationAgg ..> JobOpeningAgg : Refers to
@enduml

