@startuml

title System Sequence Diagram (SSD) - List all my applications

actor "Candidate" as U
participant ":System" as S

U -> S : Requests to list all my applications
S -> U : Receive the list of applications and their state
S -> U : Error message (if something fails)

@enduml
