@startuml

title System Sequence Diagram (SSD) - Open or Close Job Opening Phases

actor "Customer Manager" as CM
participant ":System" as S

CM -> S : Request to open/close phase
S -> CM : Asks for details
CM --> S : Provides details

S -> CM : Phase changed successfully
S -> CM : Error message (if phase change fails)

@enduml
