@startuml

title System Sequence Diagram (SSD) - Ordered List of Candidates

actor "Customer Manager" as CM
participant ":System" as S

CM -> S : Request ordered list of candidates for Job Opening

S --> CM : Ask for Job Reference
CM -> S : Provide Job Reference

S --> CM : Provide list of candidates with interview grades and confirms operation success


@enduml
