@startuml

title System Sequence Diagram (SSD) - Get an Ordered List of Candidates

actor "Customer Manager" as CM
participant ":System" as S

activate CM

CM -> S : Requests an ordered list of candidates by interview points
activate S
S --> CM : Asks for the job opening identifier
deactivate S


CM -> S : Provides the job opening identifier
activate S

S --> CM : Returns the ordered list of candidates
deactivate S


@enduml