@startuml

title SD - Register Job Opening

actor Recruiter
participant "UI : RegisterJobOpeningUI" as UI
participant "Controller : RegisterJobOpeningController" as controller
participant "JobOpeningService" as jobService
participant "JobOpening" as jobOpening
participant "JobOpeningRepository" as jobRepo

Recruiter -> UI : show()
activate UI

UI -> controller : getJobOpeningData()
activate controller

controller -> jobService : createJobOpening(data)
activate jobService

jobService -> jobOpening : new JobOpening(jobReference, jobTitle, jobState, contractType, mode, description, address, numberOfVacancies)
activate jobOpening
jobOpening --> jobService : jobOpening
deactivate jobOpening

jobService -> jobRepo : save(jobOpening)
activate jobRepo
jobRepo --> jobService : jobOpening
deactivate jobRepo

jobService --> controller : jobOpening
deactivate jobService

controller --> UI : displaySuccess(jobOpening)
deactivate controller

UI -> Recruiter : showResult()

deactivate UI

@enduml
