@startuml DomainModel
package JobApplicationAgg {
    class JobApplication {
        +id: ApplicationID
        +RequirementsEvaluation: RequirementsEvaluation
        +Interview: Interview
    }


    enum RequirementsEvaluation {
        Pending
        Accepted
        Rejected
    }

    enum NotificationStatus {
        Unsent
        Sent
    }

    JobApplication --> RequirementsEvaluation
    JobApplication --> NotificationStatus
}
@enduml