@startuml
actor Operator
participant "System" as S

Operator -> S: Asks to import candidate response
S -> Operator: Asks to select an aplication
Operator -> S: Select an aplication
S -> Operator: Request file
Operator -> S: Upload text file with requeriments
S -> Operator: Return success message


@enduml
