@startuml ClassDiagram
package UI {
    class ListMyApplicationsUI {
        -controller: ListMyApplicationsController
        +doShow(): void
        +headline(): String
    }
}

package Controller {
    class ListMyApplicationsController {
        -applicationRepository: ApplicationRepository
        -jobOpeningRepository: JobOpeningRepository
        +getAllMyApplications(candidate: Candidate): List<jobApplication>
        +getNumberOfApplications(jobOpening: JobOpening): int
    }
}

package Repository {
    class ApplicationRepository {
        +findApplicationsByCandidate(candidate: Candidate): List<jobApplication>
        +findApplicationsByJobOpening(jobOpening: JobOpening): List<jobApplication>
    }
}

package Model {
    class jobApplication {
        +id: Long
        +candidate: Candidate
        +jobOpening: JobOpening
    }

    class Candidate {
        +id: EmailAddress
    }

    class JobOpening {
        +id: JobReference
    }
}

ListMyApplicationsUI --> ListMyApplicationsController
ListMyApplicationsController --> ApplicationRepository
ApplicationRepository --> jobApplication
jobApplication --> Candidate
jobApplication --> JobOpening
@enduml
