@startuml
actor CustomerManager as CM
participant System

CM -> System: Request Display All Data of an Application
System --> CM: Return List of Applications
CM -> System: Select Application
System --> CM: Return All Data of Selected Application

@enduml
