@startuml
package JobOpeningAgg #bbaabb {
    class RecruitmentProcess<<Entity>>
    class Phase<<Entity>>
    class PhaseName<<Enum>><<Id>>
    class StartDate<<Value Object>>
    class EndDate<<Value Object>>
    class Status <<Enum>>

    RecruitmentProcess "1" --> "4..5" Phase : Is separated into
    Phase "1" --> "1" PhaseName
    Phase "1" --> "1" StartDate
    Phase "1" --> "1" EndDate
    Phase "1" --> "1" Status
}
@enduml