@startuml DomainModel
package JobOpeningAgg {

    class JobOpening {
        +id: JobReference
        +recruitmentProcess: RecruitmentProcess
    }

    class JobReference {
        + customerCode: String
        + jobNumber: int
    }

    class RecruitmentProcess {
        +id: int
        +status: RecruitmentProcessStatus
        +phases: List<Phase>
    }

    class Phase {
        +id: PhaseName
        +startDate: StartDate
        +endDate: EndDate
        +status: PhaseStatus
    }

    enum PhaseName {
            APPLICATION,
            SCREENING,
            INTERVIEWS,
            ANALYSIS,
            RESULT
    }

    class StartDate {
        +date: Date
    }

    class EndDate {
        +date: Date
    }

    enum PhaseStatus {
        Open
        Closed
    }

    enum RecruitmentProcessStatus {
        Uninitiated
        In Process
        Finished
    }

    JobOpening --> RecruitmentProcess
    JobOpening --> JobReference
    RecruitmentProcess --> RecruitmentProcessStatus
    RecruitmentProcess --> Phase : "Is separated into"
    Phase --> PhaseName
    Phase --> StartDate
    Phase --> EndDate
    Phase --> PhaseStatus
}

package JobApplicationAgg {
    class JobApplication {
        +id: ApplicationID
        +RequirementsEvaluation: RequirementsEvaluation
        +Interview: Interview
    }

    enum RequirementsEvaluation {
        Pending
        Accepted
        Rejected
    }

    class Interview {
        +InterviewGrade: int
    }

    class InterviewGrade {
        +grade: int
    }

    JobApplication --> RequirementsEvaluation
    JobApplication --> Interview
    JobApplication --> JobOpening : Refers to
    Interview --> InterviewGrade
}

package RankAgg {
    class Rank {
        +id: Long
        +rankStatus: RankStatus
    }

    enum RankStatus {
        Started
        Finished
    }

    Rank --> RankStatus
    JobOpening --> Rank : "has"
}

@enduml