@startuml
actor CustomerManager
boundary PhasesUI
control PhasesController
entity PhaseValidatorService
entity RecruitmentProcess
participant PersistenceContext
database JobOpeningRepository
database ApplicationRepository
database RankRepository

-> PhasesUI: doShow()
activate PhasesUI
PhasesUI -> PhasesController : create
activate PhasesController
PhasesController -> PersistenceContext : repositories().jobOpening()
activate PersistenceContext
PersistenceContext --> PhasesController : jobOpeningRepository : JobOpeningRepository
deactivate PersistenceContext
PhasesController --> PhasesUI : controller : PhasesController
deactivate PhasesController
PhasesUI --> CustomerManager: Asks for JobReference
CustomerManager --> PhasesUI: Insert JobReference
PhasesUI -> PhasesController: validateJobReference(jobReference : JobReference)
activate PhasesController
PhasesController -> JobOpeningRepository: findJobOpeningByJobReference(JobReference)
activate JobOpeningRepository
JobOpeningRepository --> PhasesController: jobOpening : JobOpening
deactivate JobOpeningRepository
PhasesController -> PhaseValidatorService : create(recruitmentProcess : RecruitmentProcess)
activate PhaseValidatorService
PhaseValidatorService -> PersistenceContext : repositories().application()
activate PersistenceContext
PersistenceContext --> PhaseValidatorService : applicationRepository : ApplicationRepository
deactivate PersistenceContext
PhaseValidatorService -> PersistenceContext : repositories().rank()
activate PersistenceContext
PersistenceContext --> PhaseValidatorService : rankRepository : RankRepository
deactivate PersistenceContext
PhaseValidatorService --> PhasesController: phaseValidatorService : PhaseValidatorService
deactivate PhaseValidatorService
PhasesController -> PhaseValidatorService: validatePhaseTransition()
note right
The method/methods called will
depend on the current phase of
the recruitment process.
end note
PhaseValidatorService -> RankRepository : findRankByJobReference(jobReference : JobReference)
activate RankRepository
RankRepository --> PhaseValidatorService: rank : Rank
deactivate RankRepository
PhaseValidatorService -> ApplicationRepository : countApplicatiosByJobReference(jobReference : JobReference)
activate ApplicationRepository
ApplicationRepository --> PhaseValidatorService: numberOfApplications : int
deactivate ApplicationRepository
PhaseValidatorService -> ApplicationRepository : countApplicationScreeningByJobReference(jobReference : JobReference)
activate ApplicationRepository
ApplicationRepository --> PhaseValidatorService: numberOfApplicationsScreening : int
deactivate ApplicationRepository
PhaseValidatorService -> ApplicationRepository : countApplicationInterviewsByJobReference(jobReference : JobReference)
activate ApplicationRepository
ApplicationRepository --> PhaseValidatorService: numberOfApplicationsInterviews : int
deactivate ApplicationRepository
PhaseValidatorService -> ApplicationRepository : countApplicationResultByJobReference(jobReference : JobReference)
activate ApplicationRepository
ApplicationRepository --> PhaseValidatorService: numberOfApplicationsResults : int
deactivate ApplicationRepository
PhaseValidatorService -> PhaseValidatorService : validatePhaseTransitionForward()
PhaseValidatorService -> PhaseValidatorService : validatePhaseTransitionBackward()
PhaseValidatorService --> PhasesController: options : Iterable<String>
PhasesController --> PhasesUI: options : Iterable<String>
deactivate PhasesController
PhasesUI --> CustomerManager: Show options
CustomerManager --> PhasesUI: Choose option
PhasesUI -> PhasesController: ProcessTransition(chosenOption : String)
activate PhasesController
alt chosenOption == "Forward"
PhasesController -> RecruitmentProcess: nextPhase()
else chosenOption == "Backward"
PhasesController -> RecruitmentProcess: previousPhase()
end
PhasesController -> JobOpeningRepository : save(recruitmentProcess : RecruitmentProcess)

PhasesController --> PhasesUI: Display confirmation or error
deactivate PhasesController
PhasesUI --> CustomerManager: Show confirmation or error
deactivate PhasesUI
@enduml
