@startuml
title US1017 - Upload Candidate Requirements

actor "Operator" as O
participant ":System" as S


O -> S : requests to upload a candidate requirements file
activate S

S -> O : requests candidate requirements file
deactivate S

O -> S : uploads candidate requirements file
activate S

S -> O : validate syntax and confirms the upload was successful


deactivate S

@enduml
